- id: "no-debug-statements"
  name: "No Debug Statements"
  entry: no-debug-statements/run-no-debug-statements.sh
  language: "script"
  description: "This checks that no debug statements are left in python files"